name: app
version: 2.2.26+48
publish_to: none
description: A new project create by md.hurab@gmail.com .
environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # DI & State management
  flutter_bloc: ^8.1.2
  get_it: ^7.4.0

  dartz: ^0.10.1
  equatable: ^2.0.5

  get_storage: ^2.0.2
  get: ^4.6.6
  cached_network_image: ^3.0.0
  introduction_screen: ^3.1.12
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.0.0
  flutter_widget_from_html: ^0.14.11
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  lottie: ^2.7.0
  fluttertoast: any
  url_launcher: ^6.0.9
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.0

  shared_preferences: ^2.0.6
  flutter_secure_storage: ^8.0.0

  image_picker: ^1.0.7
  flutter_rating_bar: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.14.0
  flutter_cached_pdfview: ^0.4.1
  path_provider: ^2.0.4
  permission_handler: any
  flutter_local_notifications: ^17.2.1+2
  flutter_math_fork: ^0.7.2
  google_maps_flutter: ^2.0.0
  map_picker: ^0.0.3
  geocoding: ^2.2.0
  auto_size_text: ^3.0.0
  analog_clock: ^0.1.1
  dotted_decoration: ^2.0.0
  timeago: ^3.3.0
  flutter_inappwebview: ^6.0.0
  flutter_native_timezone: any
  rxdart: any
  timezone: any
  firebase_messaging: ^14.7.4
  firebase_core: ^2.24.2
  firebase_core_platform_interface: ^5.0.0
  expandable: ^5.0.1
  notification_permissions: ^0.6.1
  device_info_plus: any
  geolocator: any
  pull_down_button: ^0.9.3
  webview_flutter: any
  #appspector: ^0.9.0
  connectivity_plus: ^3.0.6
  flutter_cache_manager: ^3.3.1
  freezed: ^2.4.5
  sn_progress_dialog: ^1.1.3
  percent_indicator: ^4.2.3
  simple_time_range_picker: ^0.0.5

#H

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter_icons:
  android: "ic_launcher"
  ios: false
  #  image_path: "assets/FitFatAppIcon.png"
  #  image_path: "assets/fitoverfat-logo.png"
  #  image_path: "assets/logo_transperrant.png"
  image_path: "assets/big_logo.png"

##flutter pub run flutter_launcher_icons:main
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/icons/
    - assets/water/
    - assets/animations/

  fonts:
    - family: appFont
      fonts:
        - asset: assets/fonts/f-regular.otf
        - asset: assets/fonts/f-light.otf
          weight: 100
        - asset: assets/fonts/f-bold.otf
          weight: 700

    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
    - family: Mogra
      fonts:
        - asset: assets/fonts/Mogra-Regular.ttf

#    - family: Inter
#      fonts:
#        - asset: assets/fonts/inter/Inter_24pt-Bold.ttf
#        - asset: assets/fonts/inter/Inter_24pt-Light.ttf
#        - asset: assets/fonts/inter/Inter_24pt-Medium.ttf
#        - asset: assets/fonts/inter/Inter_24pt-Regular.ttf