name: app
version: 1.0.0+1
publish_to: none
description: A new project create by md.hurab@gmail.com .
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.2
  get: 4.1.4
  cached_network_image: ^3.0.0
  introduction_screen: ^2.1.0
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.0.0
  flutter_widget_from_html: ^0.6.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_launcher_icons: ^0.9.0
#
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/img/ic_logo.png"
##flutter pub run flutter_launcher_icons:main
flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: appFont
      fonts:
        - asset: assets/fonts/f-regular.ttf
        - asset: assets/fonts/f-light.ttf
          weight: 100
        - asset: assets/fonts/f-bold.ttf
          weight: 700
