name: app
version: 2.2.8+28
publish_to: none
description: A new project create by md.hurab@gmail.com .
environment:
  sdk: ">=2.18.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.2
  get: 4.1.4
  cached_network_image: ^3.0.0
  introduction_screen: ^2.1.0
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.0.0
  flutter_widget_from_html: ^0.6.1
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  dio: ^4.0.0
  lottie: ^1.1.0
  fluttertoast: any
  url_launcher: ^6.0.9
  flutter_html: ^2.1.1
  shared_preferences: ^2.0.6
  image_picker: ^0.8.3+2
  flutter_rating_bar: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.12.0
  flutter_cached_pdfview: ^0.4.1
  path_provider: ^2.0.4
  permission_handler: any
  flutter_local_notifications: ^12.0.4
  flutter_math_fork: ^0.4.2
  google_maps_flutter: ^2.0.0
  map_picker: ^0.0.3
  geocoding: 2.0.0
  auto_size_text: ^3.0.0
  analog_clock: ^0.1.1
  dotted_decoration: ^2.0.0
  timeago: ^3.3.0
  flutter_inappwebview: ^5.3.2
  flutter_native_timezone: any
  rxdart: any
  timezone: any
  firebase_messaging: any
  firebase_core: ^1.12.0
  firebase_core_platform_interface: 4.5.1
  expandable: ^5.0.1
  notification_permissions: ^0.6.1
  device_info_plus: any
  geolocator: any
  pull_down_button: ^0.9.3
  intl: any
#  appspector: ^0.9.0



dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter_icons:
  android: "ic_launcher"
  ios: false
  #  image_path: "assets/FitFatAppIcon.png"
  #  image_path: "assets/fitoverfat-logo.png"
  #  image_path: "assets/logo_transperrant.png"
  image_path: "assets/big_logo.png"

##flutter pub run flutter_launcher_icons:main
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/icons/

  fonts:
    - family: appFont
      fonts:
        - asset: assets/fonts/f-regular.otf
        - asset: assets/fonts/f-light.otf
          weight: 100
        - asset: assets/fonts/f-bold.otf
          weight: 700
