name: app
version: 1.0.0+1
publish_to: none
description: A new project create by md.hurab@gmail.com .
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.2
  get: 4.1.4
  cached_network_image: ^3.0.0
  introduction_screen: ^2.1.0
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.0.0
  flutter_widget_from_html: ^0.6.1
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  dio: ^4.0.0
  lottie: ^1.1.0
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.9
  flutter_html: ^2.1.1
  shared_preferences: ^2.0.6
  image_picker: ^0.8.3+2
  flutter_rating_bar: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter_icons:
  android: "ic_launcher"
  ios: true
#  image_path: "assets/FitFatAppIcon.png"
#  image_path: "assets/fitoverfat-logo.png"
#  image_path: "assets/logo_transperrant.png"
  image_path: "assets/app_logo.png"

##flutter pub run flutter_launcher_icons:main
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/

  fonts:
    - family: appFont
      fonts:
        - asset: assets/fonts/f-regular.otf
        - asset: assets/fonts/f-light.otf
          weight: 100
        - asset: assets/fonts/f-bold.otf
          weight: 700
